"""add barcode and reorder_level to products

Revision ID: 7ad7e54df8a1
Revises: d3752bd02e9d
Create Date: 2026-08-20 18:21:45.083399

-------------------------------------------------------------------------------
THIS MIGRATION HAS BEEN EDITED BY HAND. Read why — this is the lesson.
-------------------------------------------------------------------------------

``flask db migrate`` autogenerated a first draft. Autogenerate is a *drafting
assistant*, not an author: it compares your models to the database and guesses.
It got three things wrong here, and every one of them is a classic.

1. **The unique constraint had no name.**
   Alembic wrote ``batch_op.create_unique_constraint(None, ['barcode'])`` and,
   in ``downgrade``, ``batch_op.drop_constraint(None, type_='unique')``. You
   cannot drop a constraint whose name you never chose — on PostgreSQL that
   downgrade fails outright. **Always name your constraints**, ideally through
   a naming convention on your metadata so it happens automatically.

2. **Adding a NOT NULL column to a table with existing rows.**
   ``reorder_level`` is ``nullable=False``. Existing products have no value for
   it, so the database must be told what to put there. ``server_default="5"``
   supplies it. Without a server default this migration fails the moment it
   meets a non-empty table — which is to say, in production and not in dev.

3. **No data migration.**
   A schema change that leaves the new column empty is only half the job.
   ``upgrade()`` below also **backfills** barcodes for existing rows.

Always open the generated file and read it before committing. Autogenerate
cannot see renames (it reads them as drop + add, which destroys data), cannot
see data, and cannot know your intent.
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "7ad7e54df8a1"
down_revision = "d3752bd02e9d"
branch_labels = None
depends_on = None

# Naming the constraint ONCE, here, keeps upgrade and downgrade in agreement.
BARCODE_UNIQUE = "uq_products_barcode"


def upgrade() -> None:
    """Add the two columns, then backfill barcodes for existing rows.

    ``op.batch_alter_table`` exists because **SQLite cannot ``ALTER TABLE``
    properly** — it has no ``DROP COLUMN`` or ``ALTER COLUMN`` in older
    versions, and cannot add a constraint to an existing table. Batch mode
    works around this by creating a new table with the desired shape, copying
    the rows, dropping the original, and renaming. On PostgreSQL and MySQL it
    is a harmless no-op wrapper.

    ``render_as_batch=True`` in ``app.py`` is what makes Alembic emit this
    automatically. Omit it and your SQLite migrations will fail with
    ``NotImplementedError``.
    """
    with op.batch_alter_table("products", schema=None) as batch_op:
        # Nullable: existing rows simply get NULL, no default needed.
        batch_op.add_column(sa.Column("barcode", sa.String(length=13), nullable=True))

        # NOT NULL on a populated table REQUIRES a server_default, otherwise
        # the database has no value to write into the existing rows.
        batch_op.add_column(
            sa.Column("reorder_level", sa.Integer(), server_default="5", nullable=False)
        )

        # Named, so downgrade() can drop it by name.
        batch_op.create_unique_constraint(BARCODE_UNIQUE, ["barcode"])

    # -------------------------------------------------------------------------
    # DATA MIGRATION
    # -------------------------------------------------------------------------
    # Give every existing product a placeholder barcode derived from its id.
    #
    # Note we use raw SQL through op.execute() and NOT your ORM models. This is
    # important and counter-intuitive:
    #
    #   A migration is pinned to ONE MOMENT in your schema's history. Your
    #   models.py keeps evolving. If this migration imported `Product`, then six
    #   months from now — when Product has three new columns — running it from
    #   scratch would emit SQL referencing columns that do not exist YET at this
    #   point in the history, and the migration would fail.
    #
    # Migrations must be self-contained: raw SQL, or a lightweight table
    # definition declared inline (see sa.table/sa.column).
    op.execute(
        """
        UPDATE products
           SET barcode = printf('%013d', id)
         WHERE barcode IS NULL
        """
    )


def downgrade() -> None:
    """Reverse the change exactly.

    A downgrade that has never been run is a downgrade that does not work. Test
    it: ``flask db downgrade`` then ``flask db upgrade`` again.

    Note that this **destroys the barcode data**. That is unavoidable when
    dropping a column, and it is precisely why you take a backup before running
    migrations against production.
    """
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.drop_constraint(BARCODE_UNIQUE, type_="unique")
        batch_op.drop_column("reorder_level")
        batch_op.drop_column("barcode")
